#!/bin/bash

# Set processes info
measured_process_name=run-test
measuring_process_name=measure-cpu

# Init measuring script
./measure-cpu $measured_process_name &

# Get measuring process info
measuring_processes_id=($(pgrep $measuring_process_name))
measuring_process_id=${measuring_processes_id[0]}
echo "[DEBUG] Measuring process (name/id): $measuring_process_name/$measuring_process_id"

# Init measured script
./run-test

# Stop measuring script
echo "[DEBUG] Current measuring running processes"
ps -elf | grep $measuring_process_id
echo "[DEBUG] Init kill measuring process id: $measuring_process_id"
kill $measuring_process_id
echo "[DEBUG] Current measuring running processes"
ps -elf | grep $measuring_process_id

