#!/bin/bash

if [ $# -eq 0 ]; then
  echo [ERROR] No arguments supplied
  exit 1
fi

process_name=$1
date_and_time=$(date "+%Y%m%d-%H%M%S")
results_pathname="results/metrics-cpu-$process_name-$date_and_time.txt"

echo [DEBUG] Init process name $process_name and results file $results_pathname
echo [DEBUG] Stop this script manually, for example with Control + C

ps_columns=cpuid,%cpu,%mem
echo CPU_ID CPU% MEM% TIME > $results_pathname
while :
do
  result=$(ps --no-headers -p $(pgrep $process_name) -o $ps_columns 2> /dev/null)
  if [ -n "$result" ]; then
    result="$result $(date +"%T.%N")"
    echo $result >> $results_pathname
    #echo $result
  fi
done
